<a href="https://colab.research.google.com/github/rajmayukh78/aws-ml-engineeering-task/blob/main/day9(pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data ={
    "experience:":[1,2,3,4,5,6,7,8,9,10],
    "salary":[100,200,300,400,500,600,700,800,900,1000]

}
df=pd.DataFrame(data)
print(df)

   experience:  salary
0            1     100
1            2     200
2            3     300
3            4     400
4            5     500
5            6     600
6            7     700
7            8     800
8            9     900
9           10    1000

In [3]:
print(df.head(2))

   experience:  salary
0            1     100
1            2     200

In [5]:
print(df[2:])

   experience:  salary
2            3     300
3            4     400
4            5     500
5            6     600
6            7     700
7            8     800
8            9     900
9           10    1000

In [6]:
print(df.tail())

   experience:  salary
5            6     600
6            7     700
7            8     800
8            9     900
9           10    1000

In [7]:
print(df.tail(-3))

   experience:  salary
3            4     400
4            5     500
5            6     600
6            7     700
7            8     800
8            9     900
9           10    1000

In [8]:
df=pd.DataFrame(data)

In [9]:
print(df.shape)

(10, 2)

In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   experience:  10 non-null     int64
 1   salary       10 non-null     int64
dtypes: int64(2)
memory usage: 292.0 bytes
None

In [11]:
# info
import numpy as np
data = {
    "experience":[1,2,3,4,5,6,7,8,9,np.nan],
    "salary":[np.nan,200,300,400,np.nan,600,700,800,900,1000]
}

df = pd.DataFrame(data)

# info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   experience  9 non-null      float64
 1   salary      8 non-null      float64
dtypes: float64(2)
memory usage: 292.0 bytes
None

In [13]:
df.rename(columns={'experience': 'hands_on_experience'}, inplace=True)
print(df)

   hands_on_experience  salary
0                  1.0     NaN
1                  2.0   200.0
2                  3.0   300.0
3                  4.0   400.0
4                  5.0     NaN
5                  6.0   600.0
6                  7.0   700.0
7                  8.0   800.0
8                  9.0   900.0
9                  NaN  1000.0

In [14]:
#describe
# info
import numpy as np
data = {
    "experience":[1,2,3,4,5,6,7,8,9,np.nan],
    "salary":[np.nan,200,300,400,np.nan,600,700,800,900,1000]
}

df = pd.DataFrame(data)

df.describe()

       experience       salary
count    9.000000     8.000000
mean     5.000000   612.500000
std      2.738613   290.012315
min      1.000000   200.000000
25%      3.000000   375.000000
50%      5.000000   650.000000
75%      7.000000   825.000000
max      9.000000  1000.000000

In [15]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [16]:
print(df.head())

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1

In [17]:
print(df.tail)

<bound method NDFrame.tail of    Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3>

In [18]:
print(df.shape)

(6, 5)

In [21]:
df.rename(columns={"Salary":"payment"},inplace=True)
print(df)

   Emp_ID  Name Department  payment  Experience
0     101  Amit         IT    50000           2
1     102  Riya         HR    45000           3
2     103   Raj    Finance    60000           5
3     104  Sara         IT    55000           4
4     105  John      Sales    48000           1
5     106  Neha         HR    52000           3

In [22]:
print(df.describe())

           Emp_ID       payment  Experience
count    6.000000      6.000000    6.000000
mean   103.500000  51666.666667    3.000000
std      1.870829   5316.640543    1.414214
min    101.000000  45000.000000    1.000000
25%    102.250000  48500.000000    2.250000
50%    103.500000  51000.000000    3.000000
75%    104.750000  54250.000000    3.750000
max    106.000000  60000.000000    5.000000

In [24]:
print(df['Emp_ID'])

0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64

In [ ]:
['']

In [25]:
abc=df["Emp_ID"]
print(abc)

0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64

In [26]:
df.drop("Emp_ID",axis=1,inplace=True)
print(df)

   Name Department  payment  Experience
0  Amit         IT    50000           2
1  Riya         HR    45000           3
2   Raj    Finance    60000           5
3  Sara         IT    55000           4
4  John      Sales    48000           1
5  Neha         HR    52000           3

In [27]:
# operations on columns
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)

# drop cols
df.drop("Emp_ID",axis=1,inplace=True)
print(df)

# drop multi cols
df.drop(["Name","Department"],axis=1,inplace=True)
print(df)

   Name Department  Salary  Experience
0  Amit         IT   50000           2
1  Riya         HR   45000           3
2   Raj    Finance   60000           5
3  Sara         IT   55000           4
4  John      Sales   48000           1
5  Neha         HR   52000           3
   Salary  Experience
0   50000           2
1   45000           3
2   60000           5
3   55000           4
4   48000           1
5   52000           3

In [28]:
# filter
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)
# filter one greater
print(df[df['Emp_ID'] > 104])

# 106
print(df[df['Emp_ID'] == 106])

# 30000 to 50000
# print(df[(condition one) & (condition 2)])
print(df[(df['Salary']> 30000) & (df['Salary'] < 50000)])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1

In [29]:
# operations on rows
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

# multi rows and cols
print(df.iloc[[0,1],[0,1]])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name
0     101  Amit
1     102  Riya

In [30]:
# sorting
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

# sorting ascending
print(df.sort_values("Salary",ascending=False))

# two cols
print(df.sort_values(["Salary","Experience"]))

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
5     106  Neha         HR   52000           3
0     101  Amit         IT   50000           2
4     105  John      Sales   48000           1
1     102  Riya         HR   45000           3
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1
0     101  Amit         IT   50000           2
5     106  Neha         HR   52000           3
3     104  Sara         IT   55000           4
2     103   Raj    Finance   60000           5

In [31]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [33]:
print(df.sort_values("maths",ascending=False))

       name  gender  physics  maths  english
1    rajesh    Male       96    100       95
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
2   moorthy    Male       89     90       70
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
0      arun    Male       88     87       78
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
11      Ram    Male       78     55       47
5     priya  Female       56     46       78
4      usha  Female       67     45       78
8    Dinesh    Male       56     45       67
3      raja    Male       30     25       40

In [36]:
print(df.sort_values(["maths","english"], ascending=[False, False]))

       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
9      Hema  Female       71     90       23
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
0      arun    Male       88     87       78
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
11      Ram    Male       78     55       47
5     priya  Female       56     46       78
4      usha  Female       67     45       78
8    Dinesh    Male       56     45       67
3      raja    Male       30     25       40

In [37]:
df.drop("Emp_ID",axis=1,inplace=True)
print(df)

KeyError: "['Emp_ID'] not found in axis"

In [39]:
average_scores_by_gender = df.groupby('gender')[['physics', 'maths', 'english']].mean()
display(average_scores_by_gender)

          physics      maths    english
gender
Female  73.166667  73.333333  72.666667
Male    60.375000  69.750000  67.750000

In [40]:
total_average_scores = average_scores_by_gender[['physics', 'maths', 'english']].sum(axis=1)
display(total_average_scores)

gender
Female    219.166667
Male      197.875000
dtype: float64